# Header
menu:
  Home: /
  Archives: /archives
# rss: /atom.xml

# Content
excerpt_link: read more

# Favicon
# favicon: /favicon.ico

# Settings toggle
settings: true

# Code CSS toggle
highlight: true

# Word count (needs hexo-wordcount)
word_count: false

# Google Analytics
google_analytics:
  enable: false
  acct: "UA-000000000-0"
  acct_ga4: "G-0000000000"

# IntenseDebate ID
intensedebate:
  enable: false
  acct: "00000000000000000000000000000000"

# Mastadon link
mastadon:
  enable: false
  rel: "https://some-mastadon-server/@your-username"